# Generated by Django 5.0.7 on 2024-08-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_categoy_contact_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoy',
            new_name='Category',
        ),
    ]
